# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.12
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info >= (2, 7, 0):
    def swig_import_helper():
        import importlib
        pkg = __name__.rpartition('.')[0]
        mname = '.'.join((pkg, '_equation_solver_base')).lstrip('.')
        try:
            return importlib.import_module(mname)
        except ImportError:
            return importlib.import_module('_equation_solver_base')
    _equation_solver_base = swig_import_helper()
    del swig_import_helper
elif _swig_python_version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_equation_solver_base', [dirname(__file__)])
        except ImportError:
            import _equation_solver_base
            return _equation_solver_base
        try:
            _mod = imp.load_module('_equation_solver_base', fp, pathname, description)
        finally:
            if fp is not None:
                fp.close()
        return _mod
    _equation_solver_base = swig_import_helper()
    del swig_import_helper
else:
    import _equation_solver_base
del _swig_python_version_info

try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr(self, class_type, name):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except __builtin__.Exception:
    class _object:
        pass
    _newclass = 0

class SwigPyIterator(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SwigPyIterator, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SwigPyIterator, name)

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _equation_solver_base.delete_SwigPyIterator
    __del__ = lambda self: None

    def value(self):
        return _equation_solver_base.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _equation_solver_base.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _equation_solver_base.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _equation_solver_base.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _equation_solver_base.SwigPyIterator_equal(self, x)

    def copy(self):
        return _equation_solver_base.SwigPyIterator_copy(self)

    def next(self):
        return _equation_solver_base.SwigPyIterator_next(self)

    def __next__(self):
        return _equation_solver_base.SwigPyIterator___next__(self)

    def previous(self):
        return _equation_solver_base.SwigPyIterator_previous(self)

    def advance(self, n):
        return _equation_solver_base.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _equation_solver_base.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _equation_solver_base.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _equation_solver_base.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _equation_solver_base.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _equation_solver_base.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _equation_solver_base.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self
SwigPyIterator_swigregister = _equation_solver_base.SwigPyIterator_swigregister
SwigPyIterator_swigregister(SwigPyIterator)

class cdpair(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, cdpair, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, cdpair, name)
    __repr__ = _swig_repr

    def __init__(self, *args):
        this = _equation_solver_base.new_cdpair(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_setmethods__["first"] = _equation_solver_base.cdpair_first_set
    __swig_getmethods__["first"] = _equation_solver_base.cdpair_first_get
    if _newclass:
        first = _swig_property(_equation_solver_base.cdpair_first_get, _equation_solver_base.cdpair_first_set)
    __swig_setmethods__["second"] = _equation_solver_base.cdpair_second_set
    __swig_getmethods__["second"] = _equation_solver_base.cdpair_second_get
    if _newclass:
        second = _swig_property(_equation_solver_base.cdpair_second_get, _equation_solver_base.cdpair_second_set)
    def __len__(self):
        return 2
    def __repr__(self):
        return str((self.first, self.second))
    def __getitem__(self, index): 
        if not (index % 2):
            return self.first
        else:
            return self.second
    def __setitem__(self, index, val):
        if not (index % 2):
            self.first = val
        else:
            self.second = val
    __swig_destroy__ = _equation_solver_base.delete_cdpair
    __del__ = lambda self: None
cdpair_swigregister = _equation_solver_base.cdpair_swigregister
cdpair_swigregister(cdpair)

class vp(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, vp, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, vp, name)
    __repr__ = _swig_repr

    def iterator(self):
        return _equation_solver_base.vp_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _equation_solver_base.vp___nonzero__(self)

    def __bool__(self):
        return _equation_solver_base.vp___bool__(self)

    def __len__(self):
        return _equation_solver_base.vp___len__(self)

    def __getslice__(self, i, j):
        return _equation_solver_base.vp___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _equation_solver_base.vp___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _equation_solver_base.vp___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _equation_solver_base.vp___delitem__(self, *args)

    def __getitem__(self, *args):
        return _equation_solver_base.vp___getitem__(self, *args)

    def __setitem__(self, *args):
        return _equation_solver_base.vp___setitem__(self, *args)

    def pop(self):
        return _equation_solver_base.vp_pop(self)

    def append(self, x):
        return _equation_solver_base.vp_append(self, x)

    def empty(self):
        return _equation_solver_base.vp_empty(self)

    def size(self):
        return _equation_solver_base.vp_size(self)

    def swap(self, v):
        return _equation_solver_base.vp_swap(self, v)

    def begin(self):
        return _equation_solver_base.vp_begin(self)

    def end(self):
        return _equation_solver_base.vp_end(self)

    def rbegin(self):
        return _equation_solver_base.vp_rbegin(self)

    def rend(self):
        return _equation_solver_base.vp_rend(self)

    def clear(self):
        return _equation_solver_base.vp_clear(self)

    def get_allocator(self):
        return _equation_solver_base.vp_get_allocator(self)

    def pop_back(self):
        return _equation_solver_base.vp_pop_back(self)

    def erase(self, *args):
        return _equation_solver_base.vp_erase(self, *args)

    def __init__(self, *args):
        this = _equation_solver_base.new_vp(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def push_back(self, x):
        return _equation_solver_base.vp_push_back(self, x)

    def front(self):
        return _equation_solver_base.vp_front(self)

    def back(self):
        return _equation_solver_base.vp_back(self)

    def assign(self, n, x):
        return _equation_solver_base.vp_assign(self, n, x)

    def resize(self, *args):
        return _equation_solver_base.vp_resize(self, *args)

    def insert(self, *args):
        return _equation_solver_base.vp_insert(self, *args)

    def reserve(self, n):
        return _equation_solver_base.vp_reserve(self, n)

    def capacity(self):
        return _equation_solver_base.vp_capacity(self)
    __swig_destroy__ = _equation_solver_base.delete_vp
    __del__ = lambda self: None
vp_swigregister = _equation_solver_base.vp_swigregister
vp_swigregister(vp)


def solve(input):
    return _equation_solver_base.solve(input)
solve = _equation_solver_base.solve
# This file is compatible with both classic and new-style classes.


